# Generated by Django 2.2.16 on 2020-10-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="jhgjgjhg",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
