# Generated by Django 2.2.16 on 2020-10-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_homepage_jhgjgjhg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hngjf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hghgh", models.BigIntegerField(blank=True)),
                (
                    "nbvbnvnv12213234232",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hngjf_nbvbnvnv12213234232",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
